Updates
oasis-roles/ansible_collection_osp pull request #11
Opened 2020-07-08 18:36 UTC by greg-hellings

@shwetha-h-p

2020-07-31 15:51 UTC, greg-hellings commented
@shwetha-h-p - is this ready to merge?

2020-08-07 14:17 UTC, robled requested changes

2020-08-07 14:17 UTC, robled commented on roles/director/molecule/shared/prepare.yml
> +      shell: yum clean all
Use the command module here.

2020-08-07 14:17 UTC, robled commented on roles/director/molecule/shared/prepare.yml
> +      shell: yum repolist
Use the command module here.

2020-08-18 14:46 UTC, merged